# Generated by Django 5.0.7 on 2024-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investfree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockownership",
            name="last_unit_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="stockownership",
            name="profit",
            field=models.FloatField(default=0.0),
        ),
    ]
