# Generated by Django 4.2.6 on 2024-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investfree", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="unit_price",
            new_name="buy_unit_price",
        ),
        migrations.AddField(
            model_name="transaction",
            name="sell_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sell_unit_price",
            field=models.FloatField(null=True),
        ),
    ]
