# Generated by Django 4.2.6 on 2024-07-16 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investfree", "0002_rename_unit_price_transaction_buy_unit_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="money_on_account",
            new_name="money_in_account",
        ),
    ]
